### ISSUE TITLE
androidx.startup.InitializationProvider

### ISSUE THREAD

**Issue by TimScriptov** [Frezrik/Jiagu#20]
FATAL EXCEPTION: main
Process: com.mcal.dexprotect, PID: 27440
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{JIAGU/androidx.startup.InitializationProvider}
	at android.app.ActivityThread.installProvider(ActivityThread.java:7488)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: androidx.startup.StartupException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{JIAGU/androidx.startup.InitializationProvider}
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:208)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7483)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999) 
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770) 
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7893) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
Caused by: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{JIAGU/androidx.startup.InitializationProvider}
	at android.app.ApplicationPackageManager.getProviderInfo(ApplicationPackageManager.java:637)
	at android.app.ApplicationPackageManager.getProviderInfo(ApplicationPackageManager.java:620)
	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:204)
	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2451) 
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421) 
	at android.app.ActivityThread.installProvider(ActivityThread.java:7483) 
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999) 
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770) 
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 

	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7893) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by caocaodage** [comment]
me too .help 

react-native project
