### ISSUE TITLE
加固后，重新签名。安装启动后，报这个错

### ISSUE THREAD

**Issue by jeffreyxuworld** [Frezrik/Jiagu#30]
Unable to instantiate appComponentFactory
                                                                                                    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.youkagames.gameplatform-zSQD3N1aKbPFqmvPn4a98g==/base.apk"],nativeLibraryDirectories=[/data/app/com.youkagames.gameplatform-zSQD3N1aKbPFqmvPn4a98g==/lib/arm64, /data/app/com.youkagames.gameplatform-zSQD3N1aKbPFqmvPn4a98g==/base.apk!/lib/arm64-v8a, /system/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.LoadedApk.createAppFactory(LoadedApk.java:238)
                                                                                                    	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:778)
                                                                                                    	at android.app.LoadedApk.getClassLoader(LoadedApk.java:857)
                                                                                                    	at android.app.LoadedApk.getResources(LoadedApk.java:1092)
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:2486)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6228)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:233)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1877)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:242)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7227)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)
                                                                                                    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.youkagames.gameplatform-zSQD3N1aKbPFqmvPn4a98g==/base.apk because: Failed to open dex file '/data/app/com.youkagames.gameplatform-zSQD3N1aKbPFqmvPn4a98g==/base.apk' from memory: Invalid or truncated dex file
                                                                                                    		at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                                    		at dalvik.system.DexFile.openDexFile(DexFile.java:366)
                                                                                                    		at dalvik.system.DexFile.<init>(DexFile.java:102)
                                                                                                    		at dalvik.system.DexFile.<init>(DexFile.java:76)
                                                                                                    		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
                                                                                                    		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
                                                                                                    		at dalvik.system.DexPathList.<init>(DexPathList.java:164)
                                                                                                    		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
                                                                                                    		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
                                                                                                    		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                                                                                                    		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
                                                                                                    		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
                                                                                                    		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
                                                                                                    		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
                                                                                                    		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:774)
                                                                                                    		... 12 more

**Comment by jeffreyxuworld** [comment]
还有这个错：
  Process: com.youkagames.gameplatform, PID: 25732
                                                                                                    java.lang.RuntimeException: Unable to get provider com.blankj.utilcode.util.UtilsFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7493)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                                                                    	at androidx.core.content.FileProvider.getFileProviderPathsMetaData(FileProvider.java:6)
                                                                                                    	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:4)
                                                                                                    	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:3)
                                                                                                    	at androidx.core.content.FileProvider.attachInfo(FileProvider.java:8)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7488)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
